[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
curve25519-dalek = { workspace = true }
alloy-sol-types = { workspace = true }
sp1-zkvm = "3.0.0-rc4"
fibonacci-lib = { path = "../lib" }
doprf = { path = "../../crates/doprf", default-features = false }
